{
 "title": "loki logs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Loki & Prom",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "random_value_total" },
    {
     "expr": "max_over_time(\n{filename=\"/var/log/test_extract.log\"}\n| regexp \"(?P<id>^\\\\S+) (?P<value>\\\\d+)\" \n| unwrap value | __error__=\"\" [5s] \n\n)"
    }
   ]
  },
  {
   "title": "Loki metric request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(\n{filename=\"/var/log/test_extract.log\"}\n| regexp \"(?P<id>^\\\\S+) (?P<value>\\\\d+)\" \n| unwrap value | __error__=\"\" [5s] \n\n)"
    }
   ]
  },
  {
   "title": "Loki Metric Request",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(\n{filename=\"/var/log/test_extract.log\"}\n| regexp \"(?P<id>^\\\\S+) (?P<value>\\\\d+)\" \n| unwrap value | __error__=\"\" [10s] \n\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/test_extract.log\"}"
    }
   ]
  }
 ]
}